---

- name: Delete previous bahmniapps zip file
  file:
    path: /opt/bahmni-web/etc/bahmniapps.zip
    state: absent

- name: Download bahmniapps zip file from s3 bucket
  get_url:
    url: "{{ bahmni_apps_url }}" 
    dest: /opt/bahmni-web/etc/

- name: Unlinking /var/www/bahmniapps
  command: unlink /var/www/bahmniapps

- name: Unzip bamniapps zip file
  unarchive:
    src: /opt/bahmni-web/etc/bahmniapps.zip
    dest: /opt/bahmni-web/etc/bahmniapps

- name: Linking /var/www/bahmniapps to downloaded bahmniapps
  command: ln -s /opt/bahmni-web/etc/bahmniapps /var/www/bahmniapps

- name: Remove bahmniapps zip file
  file:
    path: /opt/bahmni-web/etc/bahmniapps.zip
    state: absent

- name: Stop openmrs service
  service:
    name: openmrs
    state: stopped

- name: Remove OpenMRS web service rest omod
  shell: rm -f /opt/openmrs/modules/webservices.rest-*.omod

- name: Download OpenMRS web service rest omod
  get_url:
    url: "{{ openmrs_webservices_rest_omod }}"
    dest: /opt/openmrs/modules/
    group: bahmni
    owner: bahmni

